/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalitikRouteImport } from './routes/analitik'
import { Route as IlanlarRouteImport } from './routes/ilanlar'
import { Route as KullanicilarRouteImport } from './routes/kullanicilar'
import { Route as OnerilerRouteImport } from './routes/oneriler'
import { Route as SikayetlerRouteImport } from './routes/sikayetler'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalitikRoute = AnalitikRouteImport.update({
  id: '/analitik',
  path: '/analitik',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanlarRoute = IlanlarRouteImport.update({
  id: '/ilanlar',
  path: '/ilanlar',
  getParentRoute: () => rootRouteImport,
} as any)
const KullanicilarRoute = KullanicilarRouteImport.update({
  id: '/kullanicilar',
  path: '/kullanicilar',
  getParentRoute: () => rootRouteImport,
} as any)
const OnerilerRoute = OnerilerRouteImport.update({
  id: '/oneriler',
  path: '/oneriler',
  getParentRoute: () => rootRouteImport,
} as any)
const SikayetlerRoute = SikayetlerRouteImport.update({
  id: '/sikayetler',
  path: '/sikayetler',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/ilanlar': typeof IlanlarRoute
  '/kullanicilar': typeof KullanicilarRoute
  '/oneriler': typeof OnerilerRoute
  '/sikayetler': typeof SikayetlerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/ilanlar': typeof IlanlarRoute
  '/kullanicilar': typeof KullanicilarRoute
  '/oneriler': typeof OnerilerRoute
  '/sikayetler': typeof SikayetlerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/ilanlar': typeof IlanlarRoute
  '/kullanicilar': typeof KullanicilarRoute
  '/oneriler': typeof OnerilerRoute
  '/sikayetler': typeof SikayetlerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analitik'
    | '/ilanlar'
    | '/kullanicilar'
    | '/oneriler'
    | '/sikayetler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analitik'
    | '/ilanlar'
    | '/kullanicilar'
    | '/oneriler'
    | '/sikayetler'
  id:
    | '__root__'
    | '/'
    | '/analitik'
    | '/ilanlar'
    | '/kullanicilar'
    | '/oneriler'
    | '/sikayetler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalitikRoute: typeof AnalitikRoute
  IlanlarRoute: typeof IlanlarRoute
  KullanicilarRoute: typeof KullanicilarRoute
  OnerilerRoute: typeof OnerilerRoute
  SikayetlerRoute: typeof SikayetlerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitik': {
      id: '/analitik'
      path: '/analitik'
      fullPath: '/analitik'
      preLoaderRoute: typeof AnalitikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilanlar': {
      id: '/ilanlar'
      path: '/ilanlar'
      fullPath: '/ilanlar'
      preLoaderRoute: typeof IlanlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kullanicilar': {
      id: '/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/kullanicilar'
      preLoaderRoute: typeof KullanicilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oneriler': {
      id: '/oneriler'
      path: '/oneriler'
      fullPath: '/oneriler'
      preLoaderRoute: typeof OnerilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sikayetler': {
      id: '/sikayetler'
      path: '/sikayetler'
      fullPath: '/sikayetler'
      preLoaderRoute: typeof SikayetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalitikRoute: AnalitikRoute,
  IlanlarRoute: IlanlarRoute,
  KullanicilarRoute: KullanicilarRoute,
  OnerilerRoute: OnerilerRoute,
  SikayetlerRoute: SikayetlerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
